import { Octokit } from "@octokit/rest";
import { generateContent } from './contentStrategies.js';

export async function pushDailyUpdate(userToken, repoName, contentMessage, contentStrategy = 'learning-log', username = null) {
  // Initialize Octokit with the USER'S token, not your app's generic token
  const octokit = new Octokit({ 
    auth: userToken,
    request: {
      timeout: 15000, // 15 second timeout
      retries: 2,     // Retry up to 2 times on failure
    }
  });
  
  const [owner, repo] = repoName.split('/'); // e.g., "krdevanshu06/daily-log"
  const path = 'README.md';

  try {
    console.log(`Attempting to update ${repoName} with ${contentStrategy} strategy...`);

    // 1. Get the current README (we need the SHA to update it)
    // If file doesn't exist, this throws error, which we catch to create new file
    let fileSha;
    let originalContent = "";

    try {
      const { data: fileData } = await octokit.repos.getContent({
        owner,
        repo,
        path,
      });
      fileSha = fileData.sha;
      originalContent = Buffer.from(fileData.content, 'base64').toString('utf-8');
    } catch (err) {
      console.log("README not found, creating new one.");
    }
    
    // 2. Generate dynamic content based on strategy
    let finalContent;
    if (contentMessage && contentMessage.trim()) {
      // Use provided message if available (manual commit)
      finalContent = contentMessage;
    } else {
      // Generate dynamic content using the selected strategy
      finalContent = await generateContent(contentStrategy, userToken, username);
    }
    
    // 3. Append new log entry with proper formatting
    const timestamp = new Date().toISOString().split('T')[0];
    const timeString = new Date().toLocaleTimeString('en-US', { 
      hour12: false, 
      hour: '2-digit', 
      minute: '2-digit' 
    });
    
    // Create structured content with better formatting
    let newContent;
    if (originalContent.trim() === '') {
      // New README - create with header
      newContent = `# DailyDiff Activity Log

## ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}

### ${timestamp} - ${timeString}
${finalContent}

---
*Generated by [DailyDiff](https://github.com/DailyDiff) - Building consistent coding habits*`;
    } else {
      // Existing README - append new entry
      newContent = `${originalContent}

### ${timestamp} - ${timeString}
${finalContent}`;
    }
    
    // 4. Push the update with enhanced commit message
    const commitMessage = contentMessage 
      ? `DailyDiff: Manual update for ${timestamp}`
      : `DailyDiff: ${contentStrategy} update for ${timestamp}`;
      
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path,
      message: commitMessage,
      content: Buffer.from(newContent).toString('base64'),
      sha: fileSha, // undefined if creating new file
    });

    console.log(`✅ Commit pushed successfully with ${contentStrategy} content!`);
    return { 
      success: true, 
      message: "Commit pushed", 
      content: finalContent,
      strategy: contentStrategy 
    };
  } catch (error) {
    console.error("❌ Failed to push commit:", error);
    
    // Provide more specific error messages
    if (error.status === 404) {
      return { success: false, error: "Repository not found. Check if the repository exists and you have access to it." };
    }
    if (error.status === 403) {
      return { success: false, error: "Permission denied. Check if your GitHub token has write access to this repository." };
    }
    if (error.status === 401) {
      return { success: false, error: "Authentication failed. Please re-login to GitHub." };
    }
    
    return { success: false, error: error.message || "Unknown error occurred" };
  }
}